title: Vidushraj Chandresekeran # your name (or website title) here
logo: "/images/anirban.jpg?raw=true" # your photo (or logo) here
is_user_page: True
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://linkedin.com/in/vidushraj5">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/vidush5">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: G-N1XS1M4QLR # your Google Analytics tracking ID here
