title: Vidushraj # your name (or website title) here
logo: "/images/Picture1.png?raw=true" # your photo (or logo) here
is_user_page: True
description: > # your text below (remove <br> elements if you don't need line breaks)
  A dedicated and experienced Data professional with 4 years of expertise in Data engineering & Data science. Passionate about exploring new technologies & techniques in data engineering to drive innovation & achieve business objectives.
  <br><br>
  <a href="https://linkedin.com/in/vidushraj5">View My LinkedIn Profile</a>
  
  
theme: jekyll-theme-minimal
# google_analytics: G-N1XS1M4QLR # your Google Analytics tracking ID here
